name: remote_pipes_router
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  grpc: ^3.0.2
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.5.3
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  # Runtime library for protocol buffers support.
  protobuf: ^2.0.0
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.4


dev_dependencies:
  pedantic: ^1.11.1
